=== abinit/abinit/scripts/deprecated/abinitRun.dtd
<!--'abinitRun' must contain one or more
    dataSet child and one timeInfo element in the order listed-->
<!ELEMENT abinitRun (dataSet+,timeInfo?)>

<!-- element timeInfo has no child and five attributes -->
<!ELEMENT timeInfo EMPTY>
<!ATTLIST timeInfo cpu NMTOKEN #REQUIRED>
<!ATTLIST timeInfo wall NMTOKEN #REQUIRED>
<!ATTLIST timeInfo day NMTOKEN #REQUIRED>
<!ATTLIST timeInfo month NMTOKEN #REQUIRED>
<!ATTLIST timeInfo year NMTOKEN #REQUIRED>

<!-- element dataSet is the core of the output. -->
<!ELEMENT dataSet (inputVariables,scfcvLoop+,bfgsMinimisation?,outputVariables)>

<!-- the variable child is meant to hold all values from keywords
     and computed variables at the beginning of the dataset. The
     geometry element is quite special and store the box geometry and
     atomic position instead of defining these informations within a
     variable element. -->
<!ELEMENT inputVariables (atom+,geometry,variable+)>
<!ELEMENT outputVariables (geometry,variable+)>

<!-- atom element is used to define id of atoms and their chemical species.
     The id of atoms is made as follow: 'a_<i>_<j>', where <i> is a
     number identifying the dataset and <j> a number itendifying the atom. -->
<!ELEMENT atom EMPTY>
<!ATTLIST atom id ID #REQUIRED>
<!ATTLIST atom znucl NMTOKEN #REQUIRED>

<!-- The geometry element gives the box definition and the atomic positions.
     Since the XML output file is intended for machine reading only,
     all lengths are given in Bohr. -->
<!ELEMENT geometry (rprimd,position+)>

<!ELEMENT rprimd EMPTY>
<!ATTLIST rprimd x1 NMTOKEN #REQUIRED>
<!ATTLIST rprimd x2 NMTOKEN #REQUIRED>
<!ATTLIST rprimd x3 NMTOKEN #REQUIRED>
<!ATTLIST rprimd y1 NMTOKEN #REQUIRED>
<!ATTLIST rprimd y2 NMTOKEN #REQUIRED>
<!ATTLIST rprimd y3 NMTOKEN #REQUIRED>
<!ATTLIST rprimd z1 NMTOKEN #REQUIRED>
<!ATTLIST rprimd z2 NMTOKEN #REQUIRED>
<!ATTLIST rprimd z3 NMTOKEN #REQUIRED>

<!-- The position element contains the position of the atom specified
     by 'atom' attribute. These coordinates are cartesian coordinates
     and given in Bohr. -->
<!ELEMENT position EMPTY>
<!ATTLIST position atom IDREF #IMPLIED>
<!ATTLIST position x NMTOKEN #REQUIRED>
<!ATTLIST position y NMTOKEN #REQUIRED>
<!ATTLIST position z NMTOKEN #REQUIRED>

<!-- The variable element uses the attribute type to know what kind of
     data are stored and the NMTOKENS allow to store values in the
     value attribute with space character as separators. -->
<!ELEMENT variable EMPTY>
<!ATTLIST variable name NMTOKEN #REQUIRED>
<!ATTLIST variable type (integer|logical|character|real|integer_array|real_array) #REQUIRED>
<!ATTLIST variable value NMTOKENS #REQUIRED>

<!-- The scfcvLoop stores data from the scfcv() routine. -->
<!ELEMENT scfcvLoop (initialConditions,scfcvStep+,status,finalConditions)>

<!ELEMENT initialConditions (geometry)>
<!-- The finalConditions element follow the results_gs_type data type. -->
<!ELEMENT finalConditions (energy,forces?)>

<!-- Energy parts are in hartree. -->
<!ELEMENT energy EMPTY>
<!ATTLIST energy type (direct|double-counting) #REQUIRED>
<!ATTLIST energy total NMTOKEN #REQUIRED>
<!ATTLIST energy kinetic NMTOKEN>
<!ATTLIST energy eigen-values NMTOKEN>
<!ATTLIST energy local NMTOKEN>
<!ATTLIST energy non-local NMTOKEN>
<!ATTLIST energy core NMTOKEN #REQUIRED>
<!ATTLIST energy hartree NMTOKEN #REQUIRED>
<!ATTLIST energy xc NMTOKEN #REQUIRED>
<!ATTLIST energy xcdc NMTOKEN>
<!ATTLIST energy ewald NMTOKEN>
<!ATTLIST energy ion-ion NMTOKEN>
<!ATTLIST energy entropy NMTOKEN>
<!ATTLIST energy electric-field NMTOKEN>
<!ATTLIST energy paw NMTOKEN>
<!ATTLIST energy pawdc NMTOKEN>
<!-- Forces are given in cartesian coordinates. -->
<!ELEMENT forces (force+)>
<!ELEMENT force EMPTY>
<!ATTLIST force atom IDREF #IMPLIED>
<!ATTLIST force x NMTOKEN #REQUIRED>
<!ATTLIST force y NMTOKEN #REQUIRED>
<!ATTLIST force z NMTOKEN #REQUIRED>

<!ELEMENT status EMPTY>
<!ATTLIST status cvState (Ok|Failed) #REQUIRED>
<!ATTLIST status stop-criterion (toldfe|toldff|tolmxf|tolvrs|tolwfr) #REQUIRED>

<!ELEMENT scfcvStep EMPTY>
<!ATTLIST scfcvStep eTotal NMTOKEN #REQUIRED>
<!ATTLIST scfcvStep deltaETotal NMTOKEN #REQUIRED>
<!ATTLIST scfcvStep maxResid NMTOKEN>
<!ATTLIST scfcvStep potResid NMTOKEN>
<!ATTLIST scfcvStep denResid NMTOKEN>
<!ATTLIST scfcvStep magn value NMTOKEN>
<!ATTLIST scfcvStep deltaForces NMTOKEN>
<!ATTLIST scfcvStep maxForces NMTOKEN>

<!-- The bfgsMinimisation stores information about the final
     status of a geometry optimisation using BFGS. -->
<!ELEMENT bfgsMinimisation (status)>

=== abinit/abinit/tests/v5/Refs/t79o_LOG.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE abinitRun SYSTEM "extras/post_processing/abinitRun.dtd">
<abinitRun>
  <dataSet>
    <scfcvLoop>
      <initialConditions>
        <geometry>
          <rprimd x1="      0.00000000E+00" x2="      5.20000000E+00" x3="      5.20000000E+00" y1="      5.20000000E+00" y2="      0.00000000E+00" y3="      5.20000000E+00" z1="      5.20000000E+00" z2="      5.20000000E+00" z3="      0.00000000E+00" />
          <position atom="a_1_1" x="      0.00000000E+00" y="      0.00000000E+00" z="      0.00000000E+00" />
          <position atom="a_1_2" x="      2.60000000E+00" y="      2.60000000E+00" z="      2.60000000E+00" />
        </geometry>
      </initialConditions>
      <scfcvStep eTotal="     -8.7062495241E+00" deltaETotal="     -8.70624952E+00" maxResid="      3.21522807E-04" potResid="      1.90249325E-01" />
      <scfcvStep eTotal="     -8.7071360053E+00" deltaETotal="     -8.86481285E-04" maxResid="      9.35859855E-10" potResid="      4.45025964E-03" />
      <scfcvStep eTotal="     -8.7071547431E+00" deltaETotal="     -1.87377921E-05" maxResid="      3.12290263E-08" potResid="      7.27443979E-05" />
      <scfcvStep eTotal="     -8.7071548897E+00" deltaETotal="     -1.46595518E-07" maxResid="      7.87528023E-10" potResid="      2.16894909E-06" />
      <scfcvStep eTotal="     -8.7071548987E+00" deltaETotal="     -8.92580587E-09" maxResid="      1.14916703E-10" potResid="      7.47104081E-08" />
      <scfcvStep eTotal="     -8.7071548991E+00" deltaETotal="     -4.61334082E-10" maxResid="      5.21881504E-12" potResid="      4.18324467E-11" />
      <scfcvStep eTotal="     -8.7071548991E+00" deltaETotal="      1.95399252E-13" maxResid="      5.55887385E-16" potResid="      1.92837661E-13" />
      <scfcvStep eTotal="     -8.7071548991E+00" deltaETotal="      3.19744231E-14" maxResid="      5.49826635E-18" potResid="      7.58371410E-16" />
      <status cvState="Ok" stop-criterion="toldfe" />
      <finalConditions>
        <energy type="direct" kinetic="      2.77579730E+00" local="     -2.39277596E+00" non-local="      2.10285078E+00" ewald="     -8.28738161E+00" chempot="      0.00000000E+00" hartree="      4.91482582E-01" core="      8.15811232E-02" xc="     -3.47870912E+00" total="     -8.70715490E+00" />
      </finalConditions>
    </scfcvLoop>
    <scfcvLoop>
      <initialConditions>
        <geometry>
          <rprimd x1="      0.00000000E+00" x2="      5.17061273E+00" x3="      5.17061273E+00" y1="      5.17061273E+00" y2="      0.00000000E+00" y3="      5.17061273E+00" z1="      5.17061273E+00" z2="      5.17061273E+00" z3="      0.00000000E+00" />
          <position atom="a_1_1" x="     -6.95966519E-24" y="      6.95966519E-24" z="     -3.26893365E-23" />
          <position atom="a_1_2" x="      2.58530637E+00" y="      2.58530637E+00" z="      2.58530637E+00" />
        </geometry>
      </initialConditions>
      <scfcvStep eTotal="     -8.7078761258E+00" deltaETotal="     -8.70787613E+00" maxResid="      7.97425396E-10" potResid="      4.50122371E-03" />
      <scfcvStep eTotal="     -8.7078968032E+00" deltaETotal="     -2.06774505E-05" maxResid="      3.27599965E-12" potResid="      2.49253016E-04" />
      <scfcvStep eTotal="     -8.7078976834E+00" deltaETotal="     -8.80140000E-07" maxResid="      4.34598050E-09" potResid="      1.77929258E-06" />
      <scfcvStep eTotal="     -8.7078976858E+00" deltaETotal="     -2.45014853E-09" maxResid="      6.80945770E-12" potResid="      2.30405550E-09" />
      <scfcvStep eTotal="     -8.7078976858E+00" deltaETotal="     -3.46744855E-12" maxResid="      1.57993854E-14" potResid="      3.57129300E-12" />
      <scfcvStep eTotal="     -8.7078976858E+00" deltaETotal="     -1.29674049E-13" maxResid="      8.19468635E-17" potResid="      2.71828640E-14" />
      <status cvState="Ok" stop-criterion="toldfe" />
      <finalConditions>
        <energy type="direct" kinetic="      2.79878159E+00" local="     -2.35830713E+00" non-local="      2.10796054E+00" ewald="     -8.33448308E+00" chempot="      0.00000000E+00" hartree="      4.83880276E-01" core="      8.29800471E-02" xc="     -3.48870992E+00" total="     -8.70789769E+00" />
      </finalConditions>
    </scfcvLoop>
    <scfcvLoop>
      <initialConditions>
        <geometry>
          <rprimd x1="      0.00000000E+00" x2="      5.11742570E+00" x3="      5.11742570E+00" y1="      5.11742570E+00" y2="      0.00000000E+00" y3="      5.11742570E+00" z1="      5.11742570E+00" z2="      5.11742570E+00" z3="      0.00000000E+00" />
          <position atom="a_1_1" x="     -2.56561471E-23" y="      2.56561471E-23" z="     -5.11211525E-23" />
          <position atom="a_1_2" x="      2.55871285E+00" y="      2.55871285E+00" z="      2.55871285E+00" />
        </geometry>
      </initialConditions>
      <scfcvStep eTotal="     -8.7082659834E+00" deltaETotal="     -8.70826598E+00" maxResid="      8.09571764E-10" potResid="      1.43974235E-02" />
      <scfcvStep eTotal="     -8.7083311730E+00" deltaETotal="     -6.51895996E-05" maxResid="      8.23736058E-12" potResid="      7.58853587E-04" />
      <scfcvStep eTotal="     -8.7083338136E+00" deltaETotal="     -2.64065482E-06" maxResid="      1.34086905E-08" potResid="      5.11848502E-06" />
      <scfcvStep eTotal="     -8.7083338206E+00" deltaETotal="     -6.97779790E-09" maxResid="      1.80150671E-11" potResid="      6.33969351E-09" />
      <scfcvStep eTotal="     -8.7083338206E+00" deltaETotal="     -8.11084533E-12" maxResid="      4.55257485E-14" potResid="      1.05067569E-11" />
      <scfcvStep eTotal="     -8.7083338206E+00" deltaETotal="     -2.07833750E-13" maxResid="      2.78588646E-16" potResid="      8.28107123E-14" />
      <status cvState="Ok" stop-criterion="toldfe" />
      <finalConditions>
        <energy type="direct" kinetic="      2.84151334E+00" local="     -2.29630384E+00" non-local="      2.11918159E+00" ewald="     -8.42110602E+00" chempot="      0.00000000E+00" hartree="      4.70007534E-01" core="      8.55943452E-02" xc="     -3.50722077E+00" total="     -8.70833382E+00" />
      </finalConditions>
    </scfcvLoop>
    <scfcvLoop>
      <initialConditions>
        <geometry>
          <rprimd x1="      0.00000000E+00" x2="      5.12925039E+00" x3="      5.12925039E+00" y1="      5.12925039E+00" y2="      0.00000000E+00" y3="      5.12925039E+00" z1="      5.12925039E+00" z2="      5.12925039E+00" z3="      0.00000000E+00" />
          <position atom="a_1_1" x="     -2.28589218E-23" y="      2.28589218E-23" z="     -4.87081671E-23" />
          <position atom="a_1_2" x="      2.56462519E+00" y="      2.56462519E+00" z="      2.56462519E+00" />
        </geometry>
      </initialConditions>
      <scfcvStep eTotal="     -8.7083559553E+00" deltaETotal="     -8.70835596E+00" maxResid="      3.68112173E-11" potResid="      7.12350135E-04" />
      <scfcvStep eTotal="     -8.7083592020E+00" deltaETotal="     -3.24672176E-06" maxResid="      4.21825560E-13" potResid="      3.77304117E-05" />
      <scfcvStep eTotal="     -8.7083593341E+00" deltaETotal="     -1.32126793E-07" maxResid="      6.56149696E-10" potResid="      2.60027944E-07" />
      <scfcvStep eTotal="     -8.7083593346E+00" deltaETotal="     -4.34784653E-10" maxResid="      1.00536202E-12" potResid="      3.05760773E-10" />
      <scfcvStep eTotal="     -8.7083593346E+00" deltaETotal="      2.00728323E-13" maxResid="      1.52072557E-15" potResid="      3.05955786E-13" />
      <scfcvStep eTotal="     -8.7083593346E+00" deltaETotal="     -1.24344979E-14" maxResid="      3.73729844E-18" potResid="      1.36611263E-15" />
      <status cvState="Ok" stop-criterion="toldfe" />
      <finalConditions>
        <energy type="direct" kinetic="      2.83190101E+00" local="     -2.31006272E+00" non-local="      2.11643860E+00" ewald="     -8.40169247E+00" chempot="      0.00000000E+00" hartree="      4.73115704E-01" core="      8.50037356E-02" xc="     -3.50306320E+00" total="     -8.70835933E+00" />
      </finalConditions>
    </scfcvLoop>
    <geometryMinimisation type="bfgs">
      <status cvState="Failed" stop-criterion="tolmxf" />
    </geometryMinimisation>
  </dataSet>
  <!-- timeInfo markup : cpu and wall attributes are given in seconds. -->
  <timeInfo day="10" month="11" year="2020" cpu="  0.65091501921415329" wall="  0.67591951299999997" />
</abinitRun>
